# Generated by Django 4.2.5 on 2023-10-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
